apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homeassistant
resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - tailscale.yaml
  - httproute.yaml
  - secrets.yaml
commonLabels:
  app: matter
