apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vaultwarden
commonLabels:
  app: vaultwarden
resources:
  - env.yaml
  - pvc.yaml
  - service.yaml
  - httproute.yaml
  - tailscale.yaml
  - deployment.yaml
