apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: seedbox
resources:
  - deployment.yaml
  - service.yaml
  - secrets.yaml
  - configmap.yaml
  - pvc.yaml
  - httproute.yaml
commonLabels:
  app: sonarr
