apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: immich
provisioner: rancher.io/local-path
parameters:
  nodePath: /mnt/ultra/immich
  pathPattern: ""
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
