apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-medias
provisioner: rancher.io/local-path
parameters:
  nodePath: /mnt/storage/medias
  pathPattern: ""
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
