apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-iot
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "macvlan",
    "master": "vlan21",
    "mode": "bridge",
    "ipam": {
    "type": "host-local",
    "subnet": "192.168.21.0/24",
    "rangeStart": "192.168.21.240",
    "rangeEnd": "192.168.21.250",
    "routes": [
    { "dst": "0.0.0.0/0" }
    ],
    "gateway": "192.168.21.1"
    }
    }'
