apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tailscale.yaml
  - longhorn-system.yaml
  - cert-manager.yaml
  - cnpg.yaml
  - nvidia.yaml
  - traefik.yaml
  - networking.yaml
  - vaultwarden.yaml
  - homeassistant.yaml
